#!/bin/bash

set -e

## Usage: codesync [<sources>...] <targetfile>

targetfile=$1
dest=$2

if [ ! -e $targetfile ]
then
  echo "Cannot find $targetfile file!"
  exit 1
fi

if [ -z $dest ]
then
  echo "Cannot find $dest destination directory!"
  exit 1
fi

#rsync_args='-aP --delete-before --exclude .git --exclude node_modules --exclude vendor'
rsync_args='-aP --delete-before --exclude .git --exclude node_modules'

function do_sync() {
  while read line
  do
    # Expand variables
    line=`eval echo $line`

    # If rsync fails, try again
    fail_count=5
    while ! rsync `echo $rsync_args` `echo $line`
    do
      fail_count=$(( fail_count - 1 ))

      if [ $fail_count -eq 0 ]
      then
        echo "Failed 5 times, exiting"
        exit 1
      fi


      echo "Failed! Retrying in 2s..."
      sleep 2
    done
  done < $targetfile
}

echo '==============='
echo 'Initial sync...'
echo '==============='
do_sync

fswatch -or --exclude='\.git/' . | while read line
do
  echo -e "\n\n"
  echo '=========='
  echo 'Syncing...'
  date
  echo '=========='
  do_sync
done
